### ISSUE TITLE
Deploying on existing Prometheus

### ISSUE THREAD

**Issue by RobertJBarron** [grafana/kubernetes-app#3]
Hi,

1. What happens if I've got an existing Prometheus configuration? 
2. The main readme says 
>  detailed instructions to deploy them manually them with kubectl

I don't see them.

Thanks!

**Comment by jtlisi** [comment]
@RobertJBarron 

If you are already running Prometheus you just need to ensure you are collecting metrics from the required exporters.

- [Node Exporter](https://github.com/prometheus/node_exporter)
- [Kube-State-Metrics](https://github.com/kubernetes/kube-state-metrics)

The rest of the metrics can be scraped from the `/metrics` endpoint on kubelet.

After installing the app and connecting to the cluster, there is a panel that generate a Prometheus scrape config for Prometheus on Kubernetes on the bottom of the cluster config page. There is also a download link for 2 static files that contain the deployment for the kube-state-metrics and node-exporter.

**Comment by MrJibbles** [comment]
Hi, I also have an existing deployment (with Node Exporter and Kube-State-Metrics) running and using a couple of Node Exporter related dashboards. However the dashboard with the plugin seem to be better! Which is the cluster URL needed for attaching the DataSource to my cluster? Prometheus is already scraping from the deployed Node Exporters/Kube-State-Metrics.
Thanks

**Comment by aramalipoor** [comment]
I have the same situation as @MrJibbles I have installed both `node-exporter` and `kube-state-metrics`.

* What's this URL config used for? And on which endpoint should it point to?
* Does the jobs names matter?

**Comment by jtlisi** [comment]
@MrJibbles @aramalipoor 

The url config required is for your kubernetes cluster, not your prometheus cluster. The cluster config page allows the kubernetes-app access to your kubernetes cluster api.

I hope this clears things up. Let me know if you have any questions.

Also @aramalipoor Job name does not matter.

**Comment by adaniline-traderev** [comment]
I have the same problem - AWS EKS uses aws-iam-authenticator utility to generate STS tokens for authentication - this creates a problem when configuring the plugin's kubernetes authentication. I've tried specifying local https://kubernetes.default.svc.cluster url, this did not seem to work.

We've already installed prometheus operator with kube-state-metrics and node-exporter

Can you clarify if it is grafana process that connects to the k8s api endpoint (though plugin)? Why is this required if all the metrics are already exposed through the prometheus endpoint?
