### ISSUE TITLE
How to create proper authentication for kubernetes

### ISSUE THREAD

**Issue by cbluth** [grafana/kubernetes-app#39]
I used helm to deploy grafana, but I cannot get it to connect to the kubernetes api. I cannot find instructions on how to create a cluserrole for grafana.

**Comment by cbluth** [comment]
For example, where can I put the kubernetes auth token?

![image](https://user-images.githubusercontent.com/6709636/44411768-941dde00-a567-11e8-91f2-b16c94b541ed.png)

**Comment by cbluth** [comment]
For example, where can I put the kubernetes token?

![image](https://user-images.githubusercontent.com/6709636/44411852-bdd70500-a567-11e8-8527-5c183bc5a872.png)

**Comment by jazoom** [comment]
I'm wondering why this needs access to the cluster at all. All this data is accessible in Prometheus.

**Comment by cmorent** [comment]
Maybe just to deploy the required kubernetes resources?

> The Deploy button will deploy the following: (1) A promtheus configmap which contains the prometheus jobs that collect metrics used by the dashboards in the kubernetes app (2) a Node Exporter deployment, and (3) a Kube-State Metrics deployment

**Comment by cbluth** [comment]
this is the solution to my issue:
https://github.com/grafana/kubernetes-app/issues/46#issuecomment-435806954
