### ISSUE TITLE
Saved but failed to connect to MYCLUSTERNAME. Error: [object Object]

### ISSUE THREAD

**Issue by DavidLambauer** [grafana/kubernetes-app#5]
Hi, I just added the kubernetes app to my Grafana v5. I already added my prometheus data source which receives metrics from kube-metrics and from the node_exporter. 

After configuring all the plugin settings, Grafana displays the following error:

```
Saved but failed to connect to MY CLUSTERNAME. Error: [object Object]
```

I guess, my settings are not correct but I am not sure how to get further help because there are no messages in the grafana log. 

Some of the dashboard panels do work, for example `Cluster Disk Usage`.
When I open a Dashboard, the following error shows: `Templating init failed
Cannot read property 'length' of undefined`

I saw the presentation at GrafanaCon and I would really like to use the app but the setup is not completely clear (at least for me).

Hope you can provide some further debugging help.

Best

**Comment by DavidLambauer** [comment]
Just trying to provide more details here: Nodes and Namespaces as vars cannot be found and/or displayed.

**Comment by jtlisi** [comment]
It sounds like the Cluster Config is incorrect. Can you open the network tab in chrome debug tools and then access the cluster config tab within the application? The call to access the deployment endpoint in kubernetes should give an idea of what is going on. Please let me know and I can see what I can do to help. Also I will look into providing more useful error messages.

@DavidLambauer

**Comment by DavidLambauer** [comment]
Yes, you're right. 

The console says:

```
Possibly unhandled rejection: {"data":{"message":"Unable to load TLS certificate"},"status":400,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"api/datasources/proxy/42/apis/apps/v1beta1/namespaces/kube-system/deployments","headers":{"X-Grafana-Org-Id":1,"Accept":"application/json, text/plain, */*"},"retry":0},"statusText":"Bad Request","xhrStatus":"complete"}
```

I am using the proxy access with CA Cert. I might need to double check the cert file?

**Comment by DavidLambauer** [comment]
The Deployment Call responds with:

```
message: "Unable to load TLS certificate"
```

**Comment by DavidLambauer** [comment]
Okay, got the error. One of the Certificates has only 4 dashes like so:

``` 
----BEGIN....-----
THE CONTENT OF THE CERT FILE
----BEGIN....-----
```

I fixed the issue and now it works perfectly fine. Thank you a lot! I just configured 10 Cluster (One for each environment) and the Plugin saved me a lot of work 💃
