### ISSUE TITLE
Panel Plugin missing for grafana-kubernetes-app plugin

### ISSUE THREAD

**Issue by hertzknight** [grafana/kubernetes-app#66]
Unable to use the K8s Container dashboard, as the Pod Filtering panel is missing. 

The error message:
`
Panel plugin with id prometheus-kubernetes-podnav-panel could not be found
`
I am using Grafana version 6.02 and using the helm chart from stable

**Comment by murbano83** [comment]
Same issue here, was working for a while, then shows the error:

<img width="505" alt="Screenshot 2019-08-06 at 15 46 00" src="https://user-images.githubusercontent.com/4415557/62545203-8c7f4400-b861-11e9-9e84-86cadb0c951d.png">

**Comment by swarkentin** [comment]
Any suggestions to resolve this?
