### ISSUE TITLE
Repo needs a description and tags 

### ISSUE THREAD

**Issue by budhrg** [grafana/kubernetes-app#9]
It would be good to have a description for the repo to get a quick understanding of what repo is meant to.

![screenshot from 2018-03-16 12-31-42](https://user-images.githubusercontent.com/1132451/37507757-2dfb86d6-2916-11e8-9c99-7e5587694046.png)

**Comment by adamcstephens** [comment]
This is done and can be closed.

**Comment by budhrg** [comment]
Sure :+1:
